project:
  type: website
  output-dir: docs
  

website:
  title: "STAT MID PROJECT"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - page2.qmd

format:
  html:
    theme: spacestone
    css: styles.css
    toc: true



